[build]
builder = "nixpacks"
buildCommand = "mvn -B clean package -DskipTests"

[deploy]
startCommand = "java -jar target/base-0.0.1-SNAPSHOT.war --spring.profiles.active=prod"

[[services]]
name = "web"
[[services.ports]]
port = 8080